# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='school',
        ),
    ]
